apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: my-ns

data:
  nginx.conf: |
    server {
        listen 8080;
        server_name localhost;
        location / {
            root /usr/share/nginx/html
            index index.html index htm;
        }
    }