#namespace block
apiVersion: v1
kind: Namespace
metadata:
  name: my-ns
  labels:
    name: my-ns
---
#deployment block
#manages version right deployment process. Builds ReplicaSet under the hood
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: my-ns #must be created imperative or declarative /kubectl create namespace my-ns/
spec:
  replicas: 1
  selector: #selector label will be === to template.metadata.labels which means that rs will manage and keep-alive /scaling + load-balancing/ all the pods with provided label
    matchLabels:
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        #user Env variables
        #if you change configs in the file env-configmap.yaml you must restart pods
        env:
        - name: MY_NAME
          value: "Anna"
        - name: MY_NAME_E
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: NAME_E
        - name: MY_AGE
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AGE
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf       
            

